/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicaveterinaria.vistas;

import clinicaveterinaria.Modelo.Conexion;
import clinicaveterinaria.Modelo.MascotaData;
import clinicaveterinaria.Modelo.VisitaDeAtencion;
import clinicaveterinaria.Modelo.VisitasData;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elinote
 */
public class VistaVisitas extends javax.swing.JInternalFrame {
    private VisitasData visitasData;
    private Conexion conexion;
    
    
    public VistaVisitas() {
        initComponents();
        try {
        conexion = new Conexion("jdbc:mysql://localhost/clinicaveterinaria", "root", "");
        visitasData = new VisitasData(conexion);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ListadoTratamientosActivos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jl_idMascota = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        jt_idMascota = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_visitaXmascota = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("VISITAS DE ATENCION POR MASCOTA");

        jl_idMascota.setText("ID MASCOTA");

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jt_visitaXmascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_visita", "id_Mascota", "id_tratamiento", "Fecha", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(jt_visitaXmascota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_idMascota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_idMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(474, 474, 474))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idMascota)
                    .addComponent(jt_idMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
         {                                          
        List<VisitaDeAtencion> visitas = new ArrayList<>();
        if(!jl_idMascota.getText().equals("")){
            if(visitasData.buscarVisita(Integer.parseInt(jl_idMascota.getText())) != null){
                
                visitas = visitasData.obtenerVisitasXMascota(Integer.parseInt(jl_idMascota.getText()));     
            
                if(!visitas.isEmpty()){
                int a= visitas.size();
                    for(int i=0;i<a;i++){

                   jt_visitaXmascota.setValueAt(visitas.get(i).getId_visita(), i, 0);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getMascota(), i, 1);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getTratamiento(), i, 2);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getFecha(), i, 3);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getDetalle(), i, 4);


                }
                }
                else
                    JOptionPane.showMessageDialog(null, "El cliente no tiene mascotas.");
            }
            else
                JOptionPane.showMessageDialog(null, "El cliente no existe.");
        }
        else
            JOptionPane.showMessageDialog(null, "Ingrese el ID del cliente a buscar.");
            
    }
    }//GEN-LAST:event_jb_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JLabel jl_idMascota;
    private javax.swing.JTextField jt_idMascota;
    private javax.swing.JTable jt_visitaXmascota;
    // End of variables declaration//GEN-END:variables
}
