/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicaveterinaria.vistas;

import clinicaveterinaria.Modelo.Conexion;
import clinicaveterinaria.Modelo.MascotaData;
import clinicaveterinaria.Modelo.VisitaDeAtencion;
import clinicaveterinaria.Modelo.VisitasData;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elinote
 */
public class VistaVisitas extends javax.swing.JInternalFrame {
    private VisitasData visitasData;
    private Conexion conexion;
    
    
    public VistaVisitas() {
        initComponents();
        try {
        conexion = new Conexion("jdbc:mysql://localhost/clinicaveterinaria", "root", "");
        visitasData = new VisitasData(conexion);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(ListadoTratamientosActivos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_visitaXmascota = new javax.swing.JTable();
        jl_idMascota = new javax.swing.JLabel();
        jt_idMascota = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISITAS DE ATENCION POR MASCOTA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jt_visitaXmascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_visita", "id_Mascota", "id_tratamiento", "Fecha", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(jt_visitaXmascota);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 611;
        gridBagConstraints.ipady = 86;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(43, 23, 54, 23);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jl_idMascota.setText("ID MASCOTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 23, 0, 0);
        jPanel1.add(jl_idMascota, gridBagConstraints);

        jt_idMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idMascotaActionPerformed(evt);
            }
        });
        jt_idMascota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idMascotaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 34, 0, 0);
        jPanel1.add(jt_idMascota, gridBagConstraints);

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 34, 0, 0);
        jPanel1.add(jb_buscar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
         {                                          
        List<VisitaDeAtencion> visitas = new ArrayList<>();
        if(!jt_idMascota.getText().equals("")){
                
                visitas = visitasData.obtenerVisitasXMascota(Integer.parseInt(jt_idMascota.getText()));     
            
                if(!visitas.isEmpty()){
                int a= visitas.size();
                    for(int i=0;i<a;i++){

                   jt_visitaXmascota.setValueAt(visitas.get(i).getId_visita(), i, 0);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getMascota().getId_mascota(), i, 1);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getTratamiento().getId_tratamiento(), i, 2);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getFecha(), i, 3);
                    jt_visitaXmascota.setValueAt(visitas.get(i).getDetalle(), i, 4);


                }
                }
                else
                    JOptionPane.showMessageDialog(null, "La mascota no tiene visitas.");
       
        }
        else
            JOptionPane.showMessageDialog(null, "Ingrese el ID del cliente a buscar.");
            
    }
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jt_idMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idMascotaActionPerformed

    private void jt_idMascotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idMascotaKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c) && c!='\u0008') {
              
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo digitos."); 
    }//GEN-LAST:event_jt_idMascotaKeyTyped
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JLabel jl_idMascota;
    private javax.swing.JTextField jt_idMascota;
    private javax.swing.JTable jt_visitaXmascota;
    // End of variables declaration//GEN-END:variables
}
