/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicaveterinaria.vistas;


import clinicaveterinaria.Modelo.VisitasData;
import clinicaveterinaria.Modelo.Conexion;
import clinicaveterinaria.Modelo.Mascota;
import clinicaveterinaria.Modelo.MascotaData;
import clinicaveterinaria.Modelo.Tratamiento;
import clinicaveterinaria.Modelo.TratamientoData;
import clinicaveterinaria.Modelo.VisitaDeAtencion;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author elinote
 */
public class VistaVisitaDeAtencion extends javax.swing.JInternalFrame {
  private VisitasData visitasData;
  private MascotaData mascotaData;
  private Conexion conexion;
    /**
     * Creates new form VistaVisitasDeAtencion
     */
    public VistaVisitaDeAtencion() {
        initComponents();
              try {
        conexion = new Conexion("jdbc:mysql://localhost/clinicaveterinaria", "root", "");
        visitasData = new VisitasData(conexion);
        mascotaData = new MascotaData(conexion);
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(VistaVisitaDeAtencion.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jl_idVisita = new javax.swing.JLabel();
        jt_idVisita = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jt_idMascota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_idTratamiento = new javax.swing.JTextField();
        jl_fecha = new javax.swing.JLabel();
        jt_fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_detalle = new javax.swing.JTextArea();
        jt_pesoActual = new javax.swing.JTextField();
        jt_pesoPromedio = new javax.swing.JTextField();
        jl_pesoActual = new javax.swing.JLabel();
        jl_pesoPromedio = new javax.swing.JLabel();
        jb_buscar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_modificar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VISITA DE ATENCIÓN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jl_idVisita.setText("ID VISITA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 19, 0, 0);
        jPanel1.add(jl_idVisita, gridBagConstraints);

        jt_idVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idVisitaActionPerformed(evt);
            }
        });
        jt_idVisita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idVisitaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 40, 0, 0);
        jPanel1.add(jt_idVisita, gridBagConstraints);

        jLabel2.setText("ID MASCOTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 19, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jt_idMascota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idMascotaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 0);
        jPanel1.add(jt_idMascota, gridBagConstraints);

        jLabel3.setText("ID TRATAMIENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 19, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jt_idTratamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idTratamientoKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 40, 0, 0);
        jPanel1.add(jt_idTratamiento, gridBagConstraints);

        jl_fecha.setText("FECHA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jl_fecha, gridBagConstraints);

        jt_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_fechaActionPerformed(evt);
            }
        });
        jt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_fechaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 0, 0);
        jPanel1.add(jt_fecha, gridBagConstraints);

        jLabel4.setText("DETALLE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 19, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        jta_detalle.setColumns(20);
        jta_detalle.setRows(5);
        jta_detalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jta_detalleKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jta_detalle);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.ipady = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jt_pesoActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_pesoActualKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 0, 0);
        jPanel1.add(jt_pesoActual, gridBagConstraints);

        jt_pesoPromedio.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 40, 0, 0);
        jPanel1.add(jt_pesoPromedio, gridBagConstraints);

        jl_pesoActual.setText("PESO ACTUAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 19, 0, 0);
        jPanel1.add(jl_pesoActual, gridBagConstraints);

        jl_pesoPromedio.setText("PESO PROMEDIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 19, 0, 0);
        jPanel1.add(jl_pesoPromedio, gridBagConstraints);

        jb_buscar.setText("Buscar");
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 160, 0, 26);
        jPanel1.add(jb_buscar, gridBagConstraints);

        jb_borrar.setText("Borrar");
        jb_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_borrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 160, 0, 26);
        jPanel1.add(jb_borrar, gridBagConstraints);

        jb_modificar.setText("Modificar");
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 160, 0, 26);
        jPanel1.add(jb_modificar, gridBagConstraints);

        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 10, 0, 0);
        jPanel1.add(jb_guardar, gridBagConstraints);

        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 15, 0, 0);
        jPanel1.add(jb_limpiar, gridBagConstraints);

        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 8, 0, 0);
        jPanel1.add(jb_cancelar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_idVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idVisitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idVisitaActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        jt_idVisita.setEnabled(true);
        jt_idVisita.setText("");
        jt_idMascota.setText("");
        jt_idTratamiento.setText("");
        jt_fecha.setText("");
        jta_detalle.setText("");
        jt_pesoActual.setText("");
        jt_pesoPromedio.setText("");
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_borrarActionPerformed
        
        int idVisita=Integer.parseInt(jt_idVisita.getText());
       
         if(idVisita != 0){
        visitasData.borrarVisita(idVisita);
         JOptionPane.showMessageDialog(null, "Borrado exitoso.");
            jb_limpiarActionPerformed(evt);
         }
         else
         {JOptionPane.showMessageDialog(null, "Visita Inexistente .");
         }
        
        
    }//GEN-LAST:event_jb_borrarActionPerformed

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
       
        if(!jt_idVisita.getText().equals("")){
            
           int id=Integer.parseInt(jt_idVisita.getText());
           VisitaDeAtencion visita=visitasData.buscarVisita(id);
           if(visita!=null){
            
        
                jt_idVisita.setText(visita.getId_visita()+"");
                jt_idMascota.setText(visita.getMascota().getId_mascota()+"");
                jt_idTratamiento.setText(visita.getTratamiento().getId_tratamiento()+"");
                DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                String fecha=visita.getFecha().format(format);
                jt_fecha.setText(fecha);
                jta_detalle.setText(visita.getDetalle());
                jt_pesoActual.setText(Double.toString(visita.getPeso_actual()));
                //double prom=visitasData.PromediarPeso(visita.getMascota());
                //visita.setPeso_promedio(prom);
                jt_pesoPromedio.setText(Double.toString(visita.getPeso_promedio()));
                //visita.getMascota().setPeso_actual(visita.getPeso_actual());
                //visita.getMascota().setPeso_promedio(prom);
                jt_idVisita.setEnabled(false);
                
                
    }//GEN-LAST:event_jb_buscarActionPerformed
    else{
            JOptionPane.showMessageDialog(null, "No existe visita con el ID ingresado.");    
            jt_idVisita.setText("");
            }
    
    }
        else
        {
            JOptionPane.showMessageDialog(null, "Ingrese el ID de la visita.");
        }  
    }       
    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
                  
      
        int idMascota= Integer.parseInt(jt_idMascota.getText());
        Mascota mascota = visitasData.buscarMascota(idMascota);
      
        int idTratamiento=Integer.parseInt(jt_idTratamiento.getText());
        Tratamiento tratamiento = visitasData.buscarTratamiento(idTratamiento);
        
        if(mascota != null){
        if(tratamiento != null){   
         
         LocalDate fecha;
         try{
               fecha=LocalDate.parse(jt_fecha.getText(),DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }
         catch(DateTimeParseException ex){
               JOptionPane.showMessageDialog(null, "Fecha incorrecta. Formato: dd/MM/aaaa");
               return;
            }
         
         
         String detalle=jta_detalle.getText();
         double pesoActual=Double.parseDouble(jt_pesoActual.getText());
         mascota.setPeso_actual(pesoActual);
        
   
        // double pesoPromedio=mascota.getPeso_promedio();
        //  jt_pesoPromedio.setText(Double.toString(pesoPromedio));
        // visitasData.PromediarPeso(mascota);
        
        double pesoPromedio = visitasData.PromediarPeso(mascota,0);
        mascota.setPeso_promedio(pesoPromedio);
        
        mascotaData.actualizarMascota(mascota);
        
        VisitaDeAtencion visita= new VisitaDeAtencion(mascota,tratamiento,fecha,detalle,pesoActual,pesoPromedio);
         
         visitasData.guardarVisita(visita);
         jt_idVisita.setText(visita.getId_visita()+"");
        jt_pesoPromedio.setText(visita.getPeso_promedio()+"");
        jt_idVisita.setEnabled(false);
        
         JOptionPane.showMessageDialog(null, "Guardado exitoso.");
        }
        else
           JOptionPane.showMessageDialog(null, "El ID del tratamiento no existe. ");
          
          
         }
          else
            JOptionPane.showMessageDialog(null, "El ID de la mascota no existe. ");
          
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed
       
       
           
           int idMascota=Integer.parseInt(jt_idMascota.getText());
            Mascota mascota = visitasData.buscarMascota(idMascota);
          
           int idTratamiento=Integer.parseInt(jt_idTratamiento.getText());
             Tratamiento tratamiento = visitasData.buscarTratamiento(idTratamiento);
             
           if(mascota != null){
            if(tratamiento != null){  
                
            
           LocalDate fecha;
             try{
           fecha=LocalDate.parse(jt_fecha.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
           }
            catch(DateTimeParseException ex){
               JOptionPane.showMessageDialog(null, "Fecha incorrecta. Formato: dd/MM/aaaa");
               return;
            }
             
           String detalle=jta_detalle.getText();          
           double pesoActual=Double.parseDouble(jt_pesoActual.getText());
           mascota.setPeso_actual(pesoActual);
          
          //double pesoPromedio=mascota.getPeso_promedio();
          //jt_pesoPromedio.setText(Double.toString(pesoPromedio));
          
            double pesoPromedio = visitasData.PromediarPeso(mascota,1);
            mascota.setPeso_promedio(pesoPromedio);
        
            mascotaData.actualizarMascota(mascota);
            
            VisitaDeAtencion visita=new VisitaDeAtencion(Integer.parseInt(jt_idVisita.getText()),mascota,tratamiento,fecha,detalle,pesoActual,pesoPromedio);
            visitasData.actualizarVisita(visita);
            
            jt_pesoPromedio.setText(visita.getPeso_promedio()+"");
            
            JOptionPane.showMessageDialog(null, "Actualizacion exitosa.");
        }
        else
           JOptionPane.showMessageDialog(null, "El ID del tratamiento no existe. ");
          
          
         }
          else
            JOptionPane.showMessageDialog(null, "El ID de la mascota no existe. ");
          
    
    }//GEN-LAST:event_jb_modificarActionPerformed

    private void jt_idVisitaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idVisitaKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c) && c!='\u0008') {
              
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo digitos."); 
               
          }
    }//GEN-LAST:event_jt_idVisitaKeyTyped

    private void jt_idMascotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idMascotaKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c) && c!='\u0008') { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo digitos."); 
               
          } 
    }//GEN-LAST:event_jt_idMascotaKeyTyped

    private void jt_idTratamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idTratamientoKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c) && c!='\u0008') { 
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo digitos."); 
               
          } 
    }//GEN-LAST:event_jt_idTratamientoKeyTyped

    private void jt_fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_fechaKeyTyped
        char c=evt.getKeyChar(); 
             
         
          if(!Character.isDigit(c) && c!='/' && c!='\u0008') {
              
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo digitos."); 
               
          }
    }//GEN-LAST:event_jt_fechaKeyTyped

    private void jta_detalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jta_detalleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jta_detalleKeyTyped

    private void jt_pesoActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_pesoActualKeyTyped
        char c=evt.getKeyChar(); 
        
       
        
          if(!Character.isDigit(c) && (c!='.' || jt_pesoActual.getText().contains(".")) && c!='\u0008') {
              
              getToolkit().beep(); 
               
              evt.consume(); 
               
              JOptionPane.showMessageDialog(null, "Ingrese solo numeros decimales."); 
               
          }
    }//GEN-LAST:event_jt_pesoActualKeyTyped

    private void jt_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_fechaActionPerformed
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JLabel jl_fecha;
    private javax.swing.JLabel jl_idVisita;
    private javax.swing.JLabel jl_pesoActual;
    private javax.swing.JLabel jl_pesoPromedio;
    private javax.swing.JTextField jt_fecha;
    private javax.swing.JTextField jt_idMascota;
    private javax.swing.JTextField jt_idTratamiento;
    private javax.swing.JTextField jt_idVisita;
    private javax.swing.JTextField jt_pesoActual;
    private javax.swing.JTextField jt_pesoPromedio;
    private javax.swing.JTextArea jta_detalle;
    // End of variables declaration//GEN-END:variables
}
